services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - picape_pg:/var/lib/postgresql/data

volumes:
  picape_pg:
