use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :picape, PicapeWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    bash: ["../bin/spawn_execute.sh", "node", "node_modules/next/dist/bin/next-dev", "-p", "4001",
            cd: Path.expand("../assets", __DIR__)]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :picape, PicapeWeb.Endpoint,
  live_reload: [
    patterns: [
      # ~r{priv/static/.*(css|png|jpeg|jpg|gif|js|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/picape_web/views/.*(ex)$},
      ~r{lib/picape_web/templates/.*(eex|slim|slime)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :picape, Picape.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "picape_dev",
  hostname: "localhost",
  pool_size: 10

import_config "#{Mix.env}.secret.exs"
