import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
config :picape, PicapeWeb.Endpoint,
  http: [port: 4010],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :picape, PicapeWeb.Endpoint,
  live_reload: [
    patterns: [
      # ~r{priv/static/.*(css|png|jpeg|jpg|gif|js|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/picape_web/views/.*(ex)$},
      ~r{lib/picape_web/templates/.*(eex|slim|slime)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"
config :logger, level: String.to_atom(System.get_env("PICAPE_LOG_LEVEL") || "debug")

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :picape, Picape.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  database: System.get_env("PICAPE_DB") || "picape_dev",
  hostname: "localhost",
  port: 5433,
  pool_size: 10

if File.exists?(Path.expand("dev.secret.exs", __DIR__)) do
  import_config "dev.secret.exs"
end
