query FetchBonusPromotionWithProducts($filterSet: PromotionsFilterSet, $id: String, $periodStart: String, $periodEnd: String, $segmentType: [BonusSegmentType], $filterUnavailableProducts: Boolean, $forcePromotionVisibility: Boolean = true, $showAllPromotionSegments: Boolean = true, $states: [BonusSegmentState!] = null) { bonusPromotions( filterSet: $filterSet input: { id: $id periodStart: $periodStart periodEnd: $periodEnd segmentType: $segmentType filterUnavailableProducts: $filterUnavailableProducts forcePromotionVisibility: $forcePromotionVisibility showAllPromotionSegments: $showAllPromotionSegments states: $states } ) { __typename id products { __typename id } } }
