query FetchBonusBoxOffers($filterSet: PromotionsFilterSet, $periodStart: String, $periodEnd: String, $forcePromotionVisibility: Boolean = true, $filterUnavailableProducts: Boolean = false, $states: [BonusSegmentState!]) { bonusPersonalPromotionBundles(validOn: $periodStart) { __typename maximumActivations error } bonusPromotions( filterSet: $filterSet input: { periodStart: $periodStart periodEnd: $periodEnd filterUnavailableProducts: $filterUnavailableProducts forcePromotionVisibility: $forcePromotionVisibility states: $states } ) { __typename id hqId title subtitle activationStatus category productCount periodStart periodEnd rawPromotionLabels { __typename defaultDescription } images { __typename url width } } }
